version: "3"
services:
  app:
    build: .
    image: xyz_app:latest
    ports:
      - "5000:5000"
    environment:
      - "custom_text=custom greeting from inside docker-compose.yml"
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tls/tls.key:/root/ssl/key.pem
      - ./tls/tls.crt:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - app
